
# general settings
name: 000_ATD-FKE_SRx2_scratch
model_type: ImageCleanModel
scale: 2
num_gpu: 8
manual_seed: 0
# find_unused_parameters: True

# dataset and data loader settings
datasets:
  train:
    task: SR
    name: DF2K
    type: PairedImageDataset
    dataroot_gt: /data/mxt_data/SR/DF2K/HR
    dataroot_lq: /data/mxt_data/SR/DF2K/LR_bicubic/X2
    filename_tmpl: '{}x2'
    io_backend:
      type: disk
    mini_batch_sizes: [4] # 8
    iters: [300000]
    gt_size: 64
    gt_sizes: [ 64 ]
#    dataset_enlarge_ratio: 1
#    prefetch_mode: ~
#    gt_size: 128
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: Set14
    type: PairedImageDataset
    dataroot_gt: /data/mxt_data/SR/SR/Set14/HR
    dataroot_lq: /data/mxt_data/SR/SR/Set14/LR_bicubic/X2
    filename_tmpl: '{}x2'
    crop_size: -1
    crop_sizes: [ -1 ]
    io_backend:
      type: disk

# network structures
network_g:
  type: ATD
  upscale: 2
  in_chans: 3
  img_size: 64
  embed_dim: 210
  depths: [6, 6, 6, 6, 6, 6,]
  num_heads: [6, 6, 6, 6, 6, 6,]
  window_size: 16
  category_size: 256
  num_tokens: 128
  reducted_dim: 20
  convffn_kernel_size: 5
  img_range: 1.
  mlp_ratio: 2
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'
  use_checkpoint: true
  ker_size: 64
  FKE: false
  FKE_last: ture
  sub_image: false
  norm_type: 'LayerNorm' # None # 'LayerNorm'
  enc_ker_layers: [ 1,1,1,1 ]
  last_ker_layers: [ 2,2,2,2 ]
  baseblock_enc_ker: [ 'EVSS', 'EVSS','EVSS','EVSS' ]
  #  baseblock_enc_ker: ['AVSBlock', 'AVSBlock','AVSBlock','AVSBlock']
  save_memorys: [ false, false, false, false, false, false ]
# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: AdamW
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.9]
  mixing_augs:
    mixup: false
    mixup_beta: 1.2
    use_identity: true
  scheduler:
    type: MultiStepLR
    milestones: [250000]
    gamma: 0.5

  total_iter: 300000
  warmup_iter: 10000

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 2
      test_y_channel: yes
    
    ssim: # metric name, can be arbitrary
      type: calculate_ssim
      crop_border: 2
      test_y_channel: yes

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
